---
- name: install vscode
  shell: brew install visual-studio-code --cask
  args:
    creates: "/Applications/Visual Studio Code.app"

- name: enable key repeating
  shell: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

- name: install extensions
  shell: code --install-extension {{item}}
  with_items:
    - vscodevim.vim
    - ms-dotnettools.csharp
    - formulahendry.dotnet-test-explorer
    - ms-mssql.mssql
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - amatiasq.sort-imports
    - mikestead.dotenv
    - msjsdiag.debugger-for-chrome
    - stylelint.vscode-stylelint
    - clinyong.vscode-css-modules

- name: copy settings
  copy: src={{item}} dest="~/Library/Application Support/Code/User/{{item}}"
  with_items:
    - settings.json
    - keybindings.json
