---
- name: install vscode
  shell: brew install visual-studio-code --cask
  args:
    creates: "/Applications/Visual Studio Code.app"

- name: install extensions
  shell: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --install-extension {{item}}
  with_items:
    - vscodevim.vim
    - ms-dotnettools.csharp
    - formulahendry.dotnet-test-explorer
    - ms-mssql.mssql
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - amatiasq.sort-imports
    - mikestead.dotenv
    - msjsdiag.debugger-for-chrome
    - stylelint.vscode-stylelint
    - clinyong.vscode-css-modules
    - ms-azuretools.vscode-docker
    - Tyriar.sort-lines
    - hashicorp.terraform
    - fabianlauer.vs-code-xml-format

- name: copy settings
  copy: src={{item}} dest="~/Library/Application Support/Code/User/{{item}}"
  with_items:
    - settings.json
    - keybindings.json

- name: enable key repeating
  shell: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

- name: add vscode specifics to .zshrc.d
  copy:
    src: .zshrc.d/vscode.sh
    dest: ~/.zshrc.d/vscode.sh
    mode: 0755
