---
- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: $HOME/.nvm/nvm.sh

- name: install nodejs {{ node_version }}
  shell: >
    source $HOME/.nvm/nvm.sh; nvm install {{ node_version }}; nvm alias default {{ node_version }}
  args:
    creates: $HOME/.nvm/versions/node/{{ node_version }}

- name: add node specifics to .bash_profile.d
  copy:
    src: bash_profile.d/node.sh
    dest: ~/.bash_profile.d/node.sh
    mode: 0755

- name: install yarn
  homebrew: name=yarn state=latest
