---
- name: install git
  homebrew: name=git state=latest

- name: copy gitconfig
  template: src=gitconfig.j2 dest=~/.gitconfig

- name: copy global .gitignore file
  copy: src=gitignore dest=~/.gitignore

- name: install ohmyzsh
  shell: >
    curl -o- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -s -- --keep-zshrc
  args:
    creates: $HOME/.oh-my-zsh

- name: add ohmyszh specifics to .zshrc.d
  copy:
    src: .zshrc.d/ohmyzsh.sh
    dest: ~/.zshrc.d/ohmyzsh.sh
    mode: 0755
