---
- name: install git + tools
  homebrew:
    name: [ 'git', 'git-extras', 'zsh-git-prompt' ]

- name: copy gitconfig
  template: src=gitconfig.j2 dest=~/.gitconfig

- name: copy global .gitignore file
  copy: src=gitignore dest=~/.gitignore

- name: add git specifics to .zshrc.d
  copy:
    src: .zshrc.d/git.sh
    dest: ~/.zshrc.d/git.sh
    mode: 0755
