---
- name: create .zshrc.d to store profile hooks
  file:
    dest: ~/.zshrc.d
    state: directory
    mode: 0755

- name: copy .zshrc
  copy: src=.zshrc dest=~/.zshrc

- name: install iterm2
  shell: brew install iterm2 --cask
  args:
    creates: /Applications/iTerm.app

- name: install tmux
  homebrew: name=tmux state=latest

- name: copy tmux.conf
  copy: src=tmux.conf dest=~/.tmux.conf

- name: add tmux specifics to .zshrc.d
  copy:
    src: .zshrc.d/tmux.sh
    dest: ~/.zshrc.d/tmux.sh
    mode: 0755

- name: install jq
  homebrew: name=jq state=latest
