---
- name: install kubectl
  homebrew: name=kubectl state=latest

- name: add kubectl specifics to .zshrc.d
  copy:
    src: .zshrc.d/kubectl.sh
    dest: ~/.zshrc.d/kubectl.sh
    mode: 0755

- name: install helm
  homebrew: name=kubernetes-helm state=latest

- name: install minikube
  homebrew_cask: name=minikube state=present
