---
- name: install rbenv
  homebrew: name=rbenv state=latest

- name: add ruby specifics to .zshrc.d
  copy:
    src: .zshrc.d/rbenv.sh
    dest: ~/.zshrc.d/rbenv.sh
    mode: 0755

- name: install ruby {{ ruby_version }} if not present
  shell: rbenv install {{ ruby_version }}
  args:
    creates: $HOME/.rbenv/versions/{{ ruby_version }}
