---
- name: install rvm
  shell: >
    curl -sSL https://get.rvm.io | bash -s stable --ignore-dotfiles
  args:
    creates: $HOME/.rvm/scripts/rvm

- name: install ruby {{ ruby_version }}
  shell: >
    source $HOME/.rvm/scripts/rvm && rvm install {{ ruby_version }} && rvm --default use {{ ruby_version }}
  args:
    creates: $HOME/.rvm/rubies/ruby-{{ ruby_version }}
  # If issues: see https://github.com/rvm/rvm/issues/4908#issuecomment-630091536

- name: add ruby specifics to .zshrc.d
  copy:
    src: .zshrc.d/rvm.sh
    dest: ~/.zshrc.d/rvm.sh
    mode: 0755
